# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c62a7318f373d0c2d5b855e320f1d126cab45a7245258ecc0d5953ed43f46750298b5d877f62a9e210c102401eda455e6710d729a77ba9eb108c4169e536df0

test:
  secret_key_base: 12dfc21d9f41bd4c93ad4252305f0826379c53e9c2ff7959e26769e417496f5f7847503171e125006e97e2cbf43836592c33f925c71a178cb6739ab84dc77e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
